### ISSUE TITLE
QUESTION: Will the list of packages for React Native get expanded?

### ISSUE THREAD

**Issue by wilcomx** [DriveQuantPublic/react-native-drivekit#85]
My apologies upfront, for posting a question in the Issues section. I wasn't sure how to reach out in a better way.

Currently only three pakcages/features are provided next to the core. My question is if other packages, like Driver Achievement, Vehicle, Group, etc, are also planned to get released for React Native. Or is this the final list? Posibly an expected timeline to share as well?

Thank you!

**Comment by DriveQuantPublic** [comment]
Our SDKs are developed in native language (Swift and Kotlin) but we now offer interfaces for React Native. This is quite new and we have prioritized the key components for the recording and analysis of trips. 

We don't have interfaces for all DriveKit components yet. We develop interfaces based on our customers' needs, the type of project and our availability. 

If you would like to tell us more about your project, please contact us at contact@drivequant.com. This way we can answer you more precisely.

Best.
